### ISSUE TITLE
Console gets no chat messages

### ISSUE THREAD

**Issue by TOLoneWolf** [Vexatos/AsieLib#11]
When AsieLib is installed no client chat messages get displayed in my server console.
As soon as I remove this library everything works. I tried it with just this installed and not chat as well.

Minecraft version: 1.7.10
Forge version: 10.13.1.1216
AsieLib-1.7.10-0.2.12

**Comment by asiekierka** [comment]
I should just sit down and remove the chat functionality/move it to a separate mod. I'll try to do this this weekend.

**Comment by TOLoneWolf** [comment]
asielib.cfg
Found out that changing B:enableChatTweaks=true to false fixes the console issues for the server.
