### ISSUE TITLE
COFHCore needs to be updated.

### ISSUE THREAD

**Issue by jznomoney** [Vexatos/AsieLib#14]
Please update your mod with cofh.

**Comment by robaimes** [comment]
For info and context: The API in asielib is an old version and is causing issues for Mekanism not being able to connect to any RF machines or transfer power.

Removing the 'cofh' folder from within the asielib.jar does fix this issue, but I doubt it would be without side effects.

The linked issue to Mekanism is here: https://github.com/aidancbrady/Mekanism/issues/1965
