### ISSUE TITLE
Mod dont loading

### ISSUE THREAD

**Issue by JLAS333** [Vexatos/AsieLib#15]
Why this is happening, it's supposed to be normal, this is happening with the latest version of AsieLib, with an old version that i was using the mod shows as activated as well as the others, and works fine, but i want to use the latest with the last fixes and stuff.

Minecraft 1.7.10
AsieLib 0.3.4
Forge 1236 (latest)
Optifine HD U B1

![asielib problem](https://cloud.githubusercontent.com/assets/10150826/5405621/6f0d78a6-818e-11e4-9922-8e379e8716bb.png)

Please, if someone know what is this please tell me how to fix it before closing the topic (just like the autor of other mod have done with me some hours ago :( ), i am not a modder, so i dont know how to fix all the issues that appears.

**Comment by Techokami** [comment]
Does this happen when Optifine is not present?

**Comment by asiekierka** [comment]
That's normal, ignore it.

**Comment by Vexatos** [comment]
It's meant because AsieLib technically consists of two mods, the actual mod AsieLib and asielibcore, the core mod is being unloaded, that's totally normal.

**Comment by JLAS333** [comment]
Oh ok, if the mod will still works thats what matters, thanks guys :)
