### ISSUE TITLE
AsieLib breaks Items for use by Tinkers' Construct

### ISSUE THREAD

**Issue by Inari-Whitebear** [Vexatos/AsieLib#16]
AsieLib: 0.3.4/0.3.7 (thats the ones i tested anyway)
Tinkers' Construct: 1.7.1c/1.8.1
Forge: 10.13.2.1240/10.13.2.1277

Without AsieLib, I can cast ingots into Ingot Casts of Tinkers' just fine and can also use ingots to make an ingot cast. With AsieLib, however, Tinkers' will not allow me to pour metal into the ingot cast, nor pour metal onto an ingot to make a cast.

Curiously, removing AsieLib again doesn't seem to instantly fix this issue, as items that have been in the inventory while AsieLib was enabled will still be broken. Only new items (created after AsieLib has already been disabled) will work properly. Once AsieLib is enabled again, the new items will also be broken, as with all items created or carried while AsieLib is enabled.

(Note: the casting with a cast/ingot already in the casting table (and working) will actually still work after turning AsieLib back on. AsieLib does not seem to affect them while in the table, only once they return to the player's inventory. So if the working cast is removed and placed in again while AsieLib is enabled, it will be now a broken cast due to having been in the inventory.)

Of course casting blank casts always works, supposedly because it doesn't need to check against a (potentially broken) item.

**Comment by Vexatos** [comment]
@asiekierka Do you have any clue why this might be happening? I can't find anything that might be causing this.
Also, @bonii-xx: Could this be an issue with TCon? I really have no idea why it is happening...

**Comment by Vexatos** [comment]
After some testing, I cannot reproduce it using the exact same versions you have been using: http://gfycat.com/OddGrimFlatfish
Do you have Gany's End installed? If you do, you could try updating that, I was told it had been doing weird stuff with metal casting.

**Comment by Inari-Whitebear** [comment]
No Gany's end ^^ Also using Java 8, wonder if that causes any issues.
