### ISSUE TITLE
ConcurrentModificationException in StreamingAudioPlayer.stopClient

### ISSUE THREAD

**Issue by gamax92** [Vexatos/AsieLib#2]
Received a java.util.ConcurrentModificationException
Running Computronics and AsieLib for MC1.7.2

Log below
http://pastebin.com/embed_iframe.php?i=5GMBzAJr

**Comment by Techokami** [comment]
Care to give some more details? I tried executing stop() on a playing tape and it didn't crash Minecraft.

**Comment by Techokami** [comment]
After discussing the issue with gamax92, this has been deemed to be more of a very rare fluke than an actual bug.

**Comment by asiekierka** [comment]
Can't you fix this by adding synchronized(...) { } on the relevant fields?

**Comment by Techokami** [comment]
That should patch it! I also applied it to other fields that do similar things, just to be safe. Everything has been tested to work correctly.
