### ISSUE TITLE
Download Website is Down

### ISSUE THREAD

**Issue by chloeprince** [Vexatos/AsieLib#20]
Asie,

Whats going on with your website? There is a ComputerCraft interface and some stiff comes up on the screen and then nothing. What happen to your site? Are you dropping Modding? Did you pass off your AsieLib and Computertronics to someone else?

**Comment by asiekierka** [comment]
Yes, I have dropped modding. Yes, I passed it all on to Vexatos. There was a link to a new wiki but the domain got taken down because it was .tk.

**Comment by Techokami** [comment]
Note to self: get in touch with Vexatos to fix this up (got a spare .com domain handy)

**Comment by Techokami** [comment]
Actually I won't need to, the address was changed to http://wiki.vex.tty.sh/start

**Comment by cocopuffs99** [comment]
That website is also down

**Comment by Vexatos** [comment]
It's not for me.

**Comment by cocopuffs99** [comment]
Ok! No problem.  Thanks for the work that you do. =)

**Comment by LemADEC** [comment]
That website is down, so it the link on the front page. Will it be part of the remake of the website early 2018?

**Comment by asiekierka** [comment]
As weird as that may sound, I haven't maintained AsieLib in over three years, but ol' Vexatos refuses to change the name...

https://files.vexatos.com/
