### ISSUE TITLE
Links in chat are not clickable anymore

### ISSUE THREAD

**Issue by BlayTheNinth** [Vexatos/AsieLib#22]
I only took a quick look at your chat tweaks, but unless I've missed something you are un-fixing the Forge fix for [MC-30864](https://bugs.mojang.com/browse/MC-30864). Ever since Minecraft 1.7+, links need to specifically have an  OPEN_URL ClickAction assigned to them.

See newChatWithLinks() in ForgeHooks.java of Minecraft Forge.

**Comment by Vexatos** [comment]
That has been added in a rather recent version of forge, more recent than the current minimum requirement for AsieLib. I'll look into it.

**Comment by Vexatos** [comment]
You can get a version with this fix [here](http://files.vex.tty.sh/AsieLib/AsieLib-1.7.10-0.4.1.jar).
