### ISSUE TITLE
I get the message "gregtech: [MC1710,MC1710]"

### ISSUE THREAD

**Issue by vrnRaptor** [Vexatos/AsieLib#24]
If I'm used simultaneously AsieLib v0.4.2 and GregTechMod v6.00.50 or older, i get the message "gregtech: [MC1710,MC1710]"

**Comment by Vexatos** [comment]
It's because AsieLib crashes with GregTech 6 Use GregTech 5 until GT 6 is considered stable. See #21, #23, asiekierka/Computronics#119 and asiekierka/Computronics#118. Read my responses there.
