### ISSUE TITLE
asielib doesn't startup with GT6

### ISSUE THREAD

**Issue by ghost** [Vexatos/AsieLib#29]
gregtech_1.7.10-6.03.11
AsieLib-1.7.10-0.4.5
https://imgur.com/a/yZv3O
[fml-client-latest.txt](https://github.com/asiekierka/AsieLib/files/392384/fml-client-latest.txt)

**Comment by Vexatos** [comment]
You need the latest [development build of asielib](http://files.vex.tty.sh/AsieLib/dev/).

Same with [Computronics](http://files.vex.tty.sh/Computronics/dev/) in case it matters.
