### ISSUE TITLE
[1.7.10] NoClassDefFoundError: pl.asie.lib.block.BlockBase

### ISSUE THREAD

**Issue by gatoborrachon** [Vexatos/AsieLib#32]
is it know why the API itself does not recognize its own .class? i know that this must be an issue with a coremod, but is it know which coremod? (maybe DragonApi?)

https://pastebin.com/ce1ZMJYg

**Comment by Vexatos** [comment]
Looks like this is caused by an outdated version of the CoFH API that you have loaded from... Technomancy+ it seems? Try installing a newer version of that, or a newer version of the CoFH API itself (e.g. CoFHCore).

**Comment by gatoborrachon** [comment]
oh, it seems to be the cause, and adding CoFHCore fixed it, many thanks
